server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:nacos:"
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ticket-service-api
          uri: lb://ticket-service
          predicates:
            - Path=/api/ticket/**
        - id: chat-service-api
          uri: lb://chat-service
          predicates:
            - Path=/api/**
        - id: chat-service-ws
          uri: lb:ws://chat-service
          predicates:
            - Path=/ws/**
        - id: chat-service-static
          uri: lb://chat-service
          predicates:
            - Path=/css/**,/js/**
        - id: chat-service-pages
          uri: lb://chat-service
          predicates:
            - Path=/,/login,/register,/agent,/agent/**,/admin
        - id: ticket-service-static
          uri: lb://ticket-service
          predicates:
            - Path=/ticket/css/**,/ticket/js/**
          filters:
            - StripPrefix=1
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/ticket/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
