server:
  port: 8082

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

deepseek:
  api-key: ${DEEPSEEK_API_KEY:sk-2c6b4b0288ef44bc9bbc91de606321de}
  base-url: https://api.deepseek.com
  model: deepseek-chat

zhipu:
  api-key: ${ZHIPU_API_KEY:84fb09b27c164d629027e62edb539f7d.PzLh5TJGdlumv4UT}
  embedding-model: embedding-3

elasticsearch:
  host: localhost
  port: 9200
  scheme: https
  username: elastic
  password: J+RNdMd5Z75iIs1U-R88